src/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/',
    include('polls.urls')),
    path('admin/', admin.site.urls),
]

src/polls/urls.py
from unittest import result
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    #ex:/polls/
    path('', views.index, name = 'index'),

    #ex:/polls/detail/5
    path('detail/<int:question_id>/',views.detail, name='detail'),

    #ex:/pools/results/5
    path('results/<int:question_id>/',views.results, name='results'),

    #ex:/polls/vote/5
    path('vote/<int:question_id>/',views.vote, name='vote'),
]

src/polls/models.py
from turtle import ondrag
from django.db import models
#le model Question prend en compte deux champs : question et pub_date(qui est la date de publication de la question)
class Question(models.Model):
    question_text = models.CharField(max_length= 200)
    pub_date = models.DateTimeField('date published')


#le model Choice prend en compte deux champs: question_text(le texte du choix) et votes(décompte des votes)
class Choice(models.Model):
        question = models.ForeignKey(Question, on_delete=models.CASCADE)
        choice_text = models.CharField(max_length=200)
        vote = models.IntegerField(default=0)

src/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,Http404
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('pub_date')[:5] #affiche les 5 dernières questions
    context = {'latest_question_list':latest_question_list}
    return render(request,'polls/index.html',context)

def detail(request,question_id):
    question = get_object_or_404(Question,pk =question_id)
    context = {'question':question}

    return render(request,'polls/detail.html',context)

def results(request,question_id):
    return HttpResponse("tu regardes les résultats de la question %s." %question_id)

def vote(request,question_id):
    return HttpResponse("tu votes pour la question %s." %question_id)

src/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{question.question_test}}</h1>
    <ul>
        {%for choice in question.choice_set.all%}
        <li>
            {{choice.choice_text}}
        </li>
        {%endfor%}
    </ul>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_test }}</h1>
            </legend>

            {% if error_message %} <p>
                <strong> {{ error_message }} </strong>
            </p>
            {%endif%}

            {%for%}
            {%endfor%}
        </fieldset>
    </form>
</body>
</html>

src/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if latest_question_list%} 
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'polls:detail' question.id%}">{{question.question_test}}</a>
                </li>
            {%endfor%}
        </ul>
    {%else%}
        <p>No polls are available</p>
    {%endif%}

</body>
</html>